name: develop

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v1.5
        with:
          src_dir: ./dev
          dest_dir: ./dev
          portal_id: ${{ secrets.develop_hubspot_portal_id }}
          personal_access_key: ${{ secrets.develop_hubspot_personal_access_key }}